<a href="https://colab.research.google.com/github/yonghoonlee-1/Activity-Classification/blob/main/activity_train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import glob
import numpy as np

path =r'mlpr20_project_data_new'

filenames1 = glob.glob(path + "/*1.txt")
filenames2 = glob.glob(path + "/*2.txt")
filenames3 = glob.glob(path + "/*3.txt")
filenames4 = glob.glob(path + "/*4.txt")
filenames5 = glob.glob(path + "/*5.txt")
filenames6 = glob.glob(path + "/*6.txt")

data1 = []
data2 = []
data3 = []
data4 = []
data5 = []
data6 = []

for filename in filenames1: 
    data1.append(np.loadtxt(filename))

for filename in filenames2: 
    data2.append(np.loadtxt(filename))

for filename in filenames3: 
    data3.append(np.loadtxt(filename))

for filename in filenames4: 
    data4.append(np.loadtxt(filename))

for filename in filenames5: 
    data5.append(np.loadtxt(filename))

for filename in filenames6: 
    data6.append(np.loadtxt(filename))

In [ ]:
print(len(data1), len(data2), len(data3), len(data4), len(data5), len(data6))

1161 1008 924 1224 1315 1337


In [ ]:
sum = len(data1) + len(data2) + len(data3) + len(data4) + len(data5) + len(data6)
print(sum)

6969


In [ ]:
target1 = np.full((1161, 1), 1, dtype=int)
target2 = np.full((1008, 1), 2, dtype=int)
target3 = np.full((924, 1), 3, dtype=int)
target4 = np.full((1224, 1), 4, dtype=int)
target5 = np.full((1315, 1), 5, dtype=int)
target6 = np.full((1337, 1), 6, dtype=int)

In [ ]:
train_input = np.concatenate((data1, data2, data3, data4, data5, data6))
train_target = np.concatenate((target1, target2, target3, target4, target5, target6))

train_input.shape, train_target.shape

((6969, 128, 6), (6969, 1))

In [ ]:
train_target[1]

array([1])

In [ ]:
train_target = train_target - 1
train_target[1]

array([0])

In [ ]:
from keras.utils import to_categorical

train_target = to_categorical(train_target)

print(train_target[1])

train_input.shape, train_target.shape

Using TensorFlow backend.


[1. 0. 0. 0. 0. 0.]


((6969, 128, 6), (6969, 6))

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, Y_train, Y_val = train_test_split(train_input, train_target, test_size=0.005, random_state=321)

X_train.shape, X_val.shape, Y_train.shape, Y_val.shape

((6934, 128, 6), (35, 128, 6), (6934, 6), (35, 6))

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Reshape, Conv1D, MaxPooling1D
from keras import models, layers

model = models.Sequential()
model.add(layers.Conv1D(250, 10, input_shape=(X_train.shape[1],X_train.shape[2]), activation='relu'))
model.add(layers.Conv1D(250, 10, activation='relu'))
model.add(MaxPooling1D(3))
model.add(layers.Conv1D(250, 10, activation='relu'))
model.add(layers.Conv1D(250, 10, activation='relu'))
model.add(layers.GlobalMaxPooling1D())
model.add(layers.Dropout(0.5))
model.add(layers.Dense(6, activation='softmax'))

print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1 (Conv1D)            (None, 119, 250)          15250     
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 110, 250)          625250    
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 36, 250)           0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 27, 250)           625250    
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 18, 250)           625250    
_________________________________________________________________
global_max_pooling1d_1 (Glob (None, 250)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 250)              

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

history = model.fit(X_train, Y_train, validation_data=(X_val, Y_val), epochs=50, batch_size=400)

Train on 6934 samples, validate on 35 samples
Epoch 1/50
6934/6934 [==============================] - 37s 5ms/step - loss: 0.9291 - accuracy: 0.6017 - val_loss: 0.4305 - val_accuracy: 0.8000
Epoch 2/50
6934/6934 [==============================] - 45s 6ms/step - loss: 0.3136 - accuracy: 0.8866 - val_loss: 0.2281 - val_accuracy: 0.9143
Epoch 3/50
6934/6934 [==============================] - 44s 6ms/step - loss: 0.1855 - accuracy: 0.9347 - val_loss: 0.1348 - val_accuracy: 0.9143
Epoch 4/50
6934/6934 [==============================] - 41s 6ms/step - loss: 0.1544 - accuracy: 0.9391 - val_loss: 0.1241 - val_accuracy: 0.9429
Epoch 5/50
6934/6934 [==============================] - 40s 6ms/step - loss: 0.1295 - accuracy: 0.9471 - val_loss: 0.1007 - val_accuracy: 0.9714
Epoch 6/50
6934/6934 [==============================] - 40s 6ms/step - loss: 0.1177 - accuracy: 0.9533 - val_loss: 0.0990 - val_accuracy: 0.9714
Epoch 7/50
6934/6934 [==============================] - 44s 6ms/step - loss: 0.1072 

In [ ]:
import pickle
from sklearn.externals import joblib

joblib.dump(model, 'mlpr_term_project.pkl') 

/Users/yonghun/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


['mlpr_term_project.pkl']

In [ ]:
prediction_results_train = []

for i in range(6934):
    result = model.predict(np.expand_dims(X_train[i], axis=0))
    result = result[0]
    prediction_results_train.append(result.argmax())

In [ ]:
prediction_results_train_arr = np.array(prediction_results_train)

In [ ]:
from numpy import argmax

Y_train_list = []

for i in range(6934):
    Y_train_list.append(argmax(Y_train[i]))

In [ ]:
Y_train_list_arr = np.array(Y_train_list)

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(Y_train_list_arr, prediction_results_train_arr))

Accuracy: 0.9867320449956735
